qp_asp_verify: add stdout colors.

diff --git a/bin/qp_asp_verify b/bin/qp_asp_verify
--- a/bin/qp_asp_verify
+++ b/bin/qp_asp_verify
@@ -109,3 +109,15 @@ fi
 echo "Verification file: '$f_name'"
 
 quartus_pgm -c "$QP_CABLE_NAME" -m as -o v\;"$f_name"
+
+RC=$?
+RED="\e[31m\e[1m"
+GREEN="\e[32m\e[1m"
+NORMAL="\e[0m"
+if [ "$RC" != 0 ]; then
+    printf "${RED}Verification failed!${NORMAL}\n"
+else
+    printf "${GREEN}Verification successful!${NORMAL}\n"
+fi
+
+exit "$RC"
