qp_asp: add stdout message about programming
return a colored message about the result of programming.

diff --git a/bin/qp_asp b/bin/qp_asp
--- a/bin/qp_asp
+++ b/bin/qp_asp
@@ -114,8 +114,15 @@ echo "File to Programming: '$f_name'" "$f_time"
 
 quartus_pgm -c "$QP_CABLE_NAME" -m as -o bpv\;"$f_name"
 
+RC=$?
+if [ "$RC" != 0 ]; then
+    printf "\e[31m\e[1mProgramming Error!\e[0m\n"
+else
+    printf "\e[32m\e[1mProgramming successful!\e[0m\n"
+fi
+
 if [ "$1" == '-g' ] || [ "$2" == '-g' ]; then
-    if [ "$?" != 0 ]; then
+    if [ "$RC" != 0 ]; then
         wish_msg "End with ERROR!" "red" &
     else
         wish_msg "Programming done." &
