qp_asp_verify: edit arguments and options
- remove file number as argument
- add cable index as option
- add automatic start as option.

diff --git a/bin/qp_asp_verify b/bin/qp_asp_verify
--- a/bin/qp_asp_verify
+++ b/bin/qp_asp_verify
@@ -5,11 +5,6 @@
 #
 # This script launches Intel Quartus Prime Programmer to verifying EPCS/EPC via ASP. The 'pof'
 # file is searched for in the current directory or given as an argument.
-#
-# For more then one program cable:
-#     set environment variable 'QP_CABLE_NAME':
-#     # export QP_CABLE_NAME=USB-Blaster[USB-0]
-#
 
 echo "+------------------------------------------------------------------------+"
 echo "|  Quartus Prime Programmer ( ASP ) verification                         |"
@@ -35,37 +30,102 @@ read_yesno () {
     done
 }
 
-if [ -z "$QP_CABLE_NAME" ]; then
-    QP_CABLE_NAME="USB-Blaster[USB-0]"
-fi
-
 usage() {
     SCRIPT_NAME="${BASH_SOURCE##*/}"
-
     echo "Usage:"
-    echo "  $SCRIPT_NAME [pof-file-name | pof-file-number]"
+    echo "  $SCRIPT_NAME [-1..9|-c=1..9] [-a|--auto] [pof-file-name]"
     echo ""
     echo "ARGS:"
     echo "    <pof-file-name>"
-    echo "            File name for verification."
-    echo "    <pof-file-number>"
-    echo "            File number for verification."
+    echo "            POF-file name for verification."
+    echo "OPTIONS:"
+    echo "    -1..9|-c=1..9"
+    echo "            Cable index from 'jtagconfig'."
+    echo "    -a|--auto"
+    echo "            Automatic programming start if only one file is find."
+    echo "Examples:"
+    echo "  $SCRIPT_NAME"
+    echo "  $SCRIPT_NAME path/project.pof"
+    echo "  $SCRIPT_NAME -2 path/project.pof"
+    echo "  $SCRIPT_NAME path/project.pof -1"
+    echo "  export QP_CABLE_NAME=USB-Blaster[USB-0] # set environment variable for Bash."
 }
 
-if [ "$#" -gt 1 ] || [ "$1" == '-h' ] || [ "$1" == '--help' ] || [ "$1" == '-help' ]; then
+if [ "$#" -gt 3 ] || [ "$1" == '-h' ] || [ "$1" == '--help' ] || [ "$1" == '-help' ]; then
     usage
     exit 0
 fi
 
-select_file ()
-{
+# Cable name
+CNAME=""
+
+get_cable_name () {
+    index="$1"
+    if ! hash jtagconfig 2>/dev/null; then
+        echo "ERROR! 'jtagconfig' was not found in PATH!"
+        exit 4
+    fi
+    IFS=$'\n' cable_arr=($(jtagconfig | sed -n 's/^[0-9]\+)\s\+// p'))
+    RC=$?
+    if [ "$RC" != 0 ]; then
+        echo "ERROR! Error during launch 'jtagconfig'!"
+        exit 5
+    fi
+    ARR_SIZE=${#cable_arr[@]}
+    if [ "$ARR_SIZE" -eq 0 ]; then
+        echo "ERROR! Can not find JTAG cable!"
+        exit 6
+    fi
+    # FIXME: remove index decrement
+    ((index--))  # 'jtagconfig' return list from '1'; cable_arr begin from '0'
+    if [ "$index" -gt "$ARR_SIZE" ] || [ "$index" -lt 0 ]; then
+        echo "ERROR! Wrong cable index specified! See 'jtagconfig'."
+        echo ""
+        usage
+        exit 7
+    fi
+    CNAME="${cable_arr[$index]}"
+}
+
+ARG1=$(echo "$1" | sed -n "s/-\(c=\)\?\([0-9]\)/\2/ p")
+ARG2=$(echo "$2" | sed -n "s/-\(c=\)\?\([0-9]\)/\2/ p")
+ARG3=$(echo "$3" | sed -n "s/-\(c=\)\?\([0-9]\)/\2/ p")
+
+if [ -n "$ARG1" ]; then
+    get_cable_name "$ARG1"
+elif [ -n "$ARG2" ]; then
+    get_cable_name "$ARG2"
+elif [ -n "$ARG3" ]; then
+    get_cable_name "$ARG3"
+elif [ -n "$QP_CABLE_NAME" ]; then
+    CNAME="$QP_CABLE_NAME"
+fi
+
+# File name
+FNAME=""
+if [ "$#" -eq 1 ] || [ "$#" -eq 2 ]; then
+    FNAME_ARG1="$1"
+    FNAME_ARG2="$2"
+    FNAME_ARG3="$3"
+    if [ -s "$1" ]; then
+        FNAME="$FNAME_ARG1"
+    elif [ -s "$2" ]; then
+        FNAME="$FNAME_ARG2"
+    elif [ -s "$3" ]; then
+        FNAME="$FNAME_ARG3"
+    fi
+fi
+
+get_file_name () {
     IFS=$'\n' f_arr=($(find . -type f \( -name "*.pof" \)))
 
+    file_num=0
     if [ ${#f_arr[@]} -gt 0 ]; then
+        echo " file(s) for programming:"
         if [ ${#f_arr[@]} -eq 1 ]; then
-            echo " ${f_arr[${1}]}"
+            file_num=0
+            echo "${f_arr[$file_num]}"
         else
-            echo " file(s) to check:"
             cnt=1
             for i in "${f_arr[@]}"; do
                 echo "$cnt: $i"
@@ -79,40 +139,39 @@ select_file ()
         echo "ERROR! There must be at least one *.pof file in dir: $(pwd)"
         exit 2
     fi
-    if [ -s "${f_arr[$file_num]}" ]; then
-        f_name=${f_arr[$file_num]}
-    else
-        f_name=${f_arr[1]}
-        if [ ${#f_arr[@]} -gt 1 ]; then
-            echo "WARNING: will be open default pof file (can't find selected file)"
-        fi
-    fi
+    f_name="${f_arr[$file_num]}"
 
-    if [ ${#f_arr[@]} -gt 1 ]; then
-        while :
-        do
-            if read_yesno "Would you like verification with file: '$f_name'" ; then
-                break;
-            else
-                echo "NOTE! Exit without verification!";
-                exit 0;
-            fi
-        done
+    if [ ! -s "$f_name" ]; then
+        echo "ERROR! Can not open selected file!"
+    else
+        FNAME=$f_name
     fi
 }
 
-if [ -n "$1" ]; then
-    if [ ! -s "$1" ]; then
-        echo "ERROR! Can't find selected file: '$1'"
-        exit 3
-    fi
-    f_name=$1
-else
-    select_file "$@"
+# Automatic verification
+AUTOPGM=0
+if [ "$1" = "-a" ] || [ "$1" = "--auto" ] \
+       || [ "$2" = "-a" ] || [ "$2" = "--auto" ] \
+       || [ "$3" = "-a" ] || [ "$3" = "--auto" ]; then
+    AUTOPGM=1
 fi
-echo "Verification file: '$f_name'"
 
-quartus_pgm -c "$QP_CABLE_NAME" -m as -o v\;"$f_name"
+
+# if the path to the file is specified as script argument, programming is started without request
+if [ -z "$FNAME" ]; then
+    get_file_name
+    if [ "$AUTOPGM" -eq 0 ]; then
+        if ! read_yesno "Would you like verification with file: $FNAME" ; then
+            echo "Exit without verification!";
+            exit 0;
+        fi
+    fi
+fi
+
+FTIME=$(date +%c -r "$FNAME")
+echo "File to Verification: $FNAME $FTIME"
+
+quartus_pgm -c "$CNAME" -m as -o v\;"$FNAME"
 
 RC=$?
 RED="\e[31m\e[1m"
