qp_jtag: add stdout message about programming
return a colored message about the result of programming.

diff --git a/bin/qp_jtag b/bin/qp_jtag
--- a/bin/qp_jtag
+++ b/bin/qp_jtag
@@ -165,3 +165,10 @@ if [[ "$f_name" == *.jic ]]; then
 else
     quartus_pgm -c "$CNAME" -m jtag -o p\;"$FNAME"
 fi
+
+RC=$?
+if [ "$RC" != 0 ]; then
+    printf "\e[31m\e[1mProgramming Error!\e[0m\n"
+else
+    printf "\e[32m\e[1mProgramming successful!\e[0m\n"
+fi
