qp_jtag: add support cable name as options.
if the path to the file is specified as script argument, programming is
started without request

diff --git a/bin/qp_jtag b/bin/qp_jtag
--- a/bin/qp_jtag
+++ b/bin/qp_jtag
@@ -6,15 +6,10 @@
 # This script launches Intel Quartus Prime Programmer to program 'sof' or 'jic' file via JTAG.
 # Program files are searched for in the current directory or given as an argument.
 #
-# For more then one program cable:
-#     set environment variable 'QP_CABLE_NAME':
-#     # export QP_CABLE_NAME=USB-Blaster[USB-0]
-#
 # NOTE:  jtagconfig.exe -n -- for describe current status information
 #
 # TODO: add handler for error: Error (213019): Can't scan JTAG chain. Error code 87.
 # for example latch command: 'jtagconfig.exe'
-# TODO: add cable name as argument
 
 echo "+------------------------------------------------------------------------+"
 echo "|  Quartus Prime Programmer ( JTAG )                                     |"
@@ -40,82 +35,131 @@ read_yesno () {
     done
 }
 
-if [ -z "$QP_CABLE_NAME" ]; then
-    QP_CABLE_NAME="USB-Blaster[USB-0]"
-fi
-
-SCRIPT_NAME="${BASH_SOURCE##*/}"
-
-if [ "$1" == '-h' ] || [ "$1" == '--help' ] || [ "$1" == '-help' ]; then
+usage() {
+    SCRIPT_NAME="${BASH_SOURCE##*/}"
     echo "Usage:"
-    echo "  $SCRIPT_NAME [prg-file-name]"
+    echo "  $SCRIPT_NAME [-1..9|-c=1..9] [prg-file-name] "
     echo ""
     echo "ARGS:"
     echo "    <prg-file-name>"
     echo "            File name for programming."
+    echo "OPTIONS:"
+    echo "    -1..9|-c=1..9"
+    echo "            Cable index from 'jtagconfig'."
+    echo ""
+    echo "Examples:"
+    echo "  $SCRIPT_NAME"
+    echo "  $SCRIPT_NAME path/project.sof"
+    echo "  $SCRIPT_NAME -2 path/project.sof"
+    echo "  $SCRIPT_NAME path/project.sof -1"
+    echo "  export QP_CABLE_NAME=USB-Blaster[USB-0] # set environment variable for Bash."
+}
+
+if [ "$#" -gt 2 ] || [ "$1" == '-h' ] || [ "$1" == '--help' ] || [ "$1" == '-help' ]; then
+    usage
     exit 0
 fi
 
-select_file ()
-{
+# Cable name
+CNAME=""
+
+get_cable_name () {
+    index="$1"
+    if ! hash jtagconfig 2>/dev/null; then
+        echo "ERROR! 'jtagconfig' was not found in PATH!"
+        exit 4
+    fi
+    IFS=$'\n' cable_arr=($(jtagconfig | sed -n 's/^[0-9]\+)\s\+// p'))
+    RC=$?
+    if [ "$RC" != 0 ]; then
+        echo "ERROR! Error during launch 'jtagconfig'!"
+        exit 5
+    fi
+    ARR_SIZE=${#cable_arr[@]}
+    if [ "$ARR_SIZE" -eq 0 ]; then
+        echo "ERROR! Can not find JTAG cable!"
+        exit 6
+    fi
+    # FIXME: remove index decrement
+    ((index--))  # 'jtagconfig' return list from '1'; cable_arr begin from '0'
+    if [ "$index" -gt "$ARR_SIZE" ] || [ "$index" -lt 0 ]; then
+        echo "ERROR! Wrong cable index specified! See 'jtagconfig'."
+        echo ""
+        usage
+        exit 7
+    fi
+    CNAME="${cable_arr[$index]}"
+}
+
+if [ -n "$QP_CABLE_NAME" ]; then
+    CNAME="$QP_CABLE_NAME"
+else
+    CINDEX=""
+    CINDEX_ARG1=$(echo "$1" | sed -n "s/-\(c=\)\?\([0-9]\)/\2/ p")
+    CINDEX_ARG2=$(echo "$2" | sed -n "s/-\(c=\)\?\([0-9]\)/\2/ p")
+    if [ -n "$CINDEX_ARG1" ]; then
+        CINDEX="$CINDEX_ARG1"
+    elif [ -n "$CINDEX_ARG2" ]; then
+        CINDEX="$CINDEX_ARG2"
+    fi
+
+    get_cable_name "$CINDEX"
+fi
+
+# File name
+FNAME=""
+if [ "$#" -eq 1 ] || [ "$#" -eq 2 ]; then
+    FNAME_ARG1="$1"
+    FNAME_ARG2="$2"
+    if [ -s "$1" ]; then
+        FNAME="$FNAME_ARG1"
+    elif [ -s "$2" ]; then
+        FNAME="$FNAME_ARG2"
+    fi
+fi
+
+get_file_name () {
     IFS=$'\n' f_arr=($(find . -type f \( -name "*.sof" -o -name "*.jic" \)))
 
+    file_num=0
     if [ ${#f_arr[@]} -gt 0 ]; then
-        if [ ${#f_arr[@]} -eq 1 ]; then
-            echo " ${f_arr[${1}]}"
-        else
-            echo " file(s) for programming:"
-            cnt=1
-            for i in "${f_arr[@]}"; do
-                echo "$cnt: $i"
-                ((cnt++))
-            done
-            echo "Select file :"
-            read -r file_num
-            ((file_num--))
-        fi
+        echo " file(s) for programming:"
+        cnt=1
+        for i in "${f_arr[@]}"; do
+            echo "$cnt: $i"
+            ((cnt++))
+        done
+        echo "Select file :"
+        read -r file_num
+        ((file_num--))
     else
         echo "ERROR! There must be at least one *.sof file in dir: $(pwd)"
         exit 2
     fi
-    if [ -s "${f_arr[$file_num]}" ]; then
-        f_name=${f_arr[$file_num]}
-    else
-        f_name=${f_arr[1]}
-        if [ ${#f_arr[@]} -gt 1 ]; then
-            echo "WARNING: will be open default sof file (can't find selected file)"
-        fi
-    fi
+    f_name="${f_arr[$file_num]}"
 
-    if [ ${#f_arr[@]} -gt 1 ]; then
-        while :
-        do
-            if read_yesno "Would you like load file: '$f_name'" ; then
-                break;
-            else
-                echo "NOTE! Exit without load!";
-                exit 0;
-            fi
-        done
+    if [ ! -s "$f_name" ]; then
+        echo "ERROR! Can not open selected file!"
+    else
+        FNAME=$f_name
     fi
 }
 
-if [ -n "$1" ]; then
-    if [ ! -s "$1" ]; then
-        echo "ERROR! Can't find selected file: '$1'"
-        exit 3
+# if the path to the file is specified as script argument, programming is started without request
+if [ -z "$FNAME" ]; then
+    get_file_name
+    if ! read_yesno "Would you like load file: $FNAME" ; then
+        echo "Exit without load!";
+        exit 0;
     fi
-    f_name=$1
-else
-    select_file "$@"
 fi
 
-f_time=$(date +%c -r "$f_name")
-echo "File to Programming: '$f_name'" "$f_time"
+FTIME=$(date +%c -r "$FNAME")
+echo "File to Programming: $FNAME " "$FTIME"
 
 if [[ "$f_name" == *.jic ]]; then
     # Blank-checking device(s), Performing CRC verification on device(s)
-    quartus_pgm -c "$QP_CABLE_NAME" -m jtag -o pvbi\;"$f_name"
+    quartus_pgm -c "$CNAME" -m jtag -o pvbi\;"$FNAME"
 else
-    quartus_pgm -c "$QP_CABLE_NAME" -m jtag -o p\;"$f_name"
+    quartus_pgm -c "$CNAME" -m jtag -o p\;"$FNAME"
 fi
