wopen: overwrite script to open GTKWave
This script was rewritten from TCL to Shell to not to fix the GTKWave
opening from TCL-Shell.

FIXME: ERROR at Fedora Linux 35, x86_64, 5.17.6-200.fc35.x86_64:
This script does not work and crashes during opening with errors:

gtkwave: /opt/altera/19.1/quartus/linux64/liblzma.so.5: no version
information available (required by gtkwave)
gtkwave: /opt/altera/19.1/quartus/linux64/liblzma.so.5: no version
information available (required by /lib64/libxml2.so.2)
gtkwave: /opt/altera/19.1/quartus/linux64/libstdc++.so.6: version
`CXXABI_1.3.8' not found (required by /lib64/libicuuc.so.69)
gtkwave: /opt/altera/19.1/quartus/linux64/libstdc++.so.6: version
`CXXABI_1.3.8' not found (required by /lib64/libicui18n.so.69)
gtkwave: /opt/altera/19.1/quartus/linux64/liblzma.so.5: no version
information available (required by /lib64/libsystemd.so.0)

diff --git a/bin/wopen b/bin/wopen
--- a/bin/wopen
+++ b/bin/wopen
@@ -1,67 +1,48 @@
-#!/usr/bin/env tclsh
+#!/usr/bin/env bash
 
 # Open GTKWave
 #
 # This script launches GTKWave with the custom command script(gtkwave_cfg.tcl),
 # searches for and opens a VCD-file in the directory from which it was launched.
 
-proc usage {} {
-    set scriptName [file tail [info script]]
-    puts "Usage:"
-    puts "       $scriptName \[vcd-fname\]"
-    puts ""
-    puts "OPTIONS:"
-    puts "    vcd-fname"
-    puts "            Name of a vcd-file."
-}
-
-set arg0 [lindex $argv 0]
-if {[string compare $arg0 "-h"] == 0} {
-    usage
+SCRIPT_NAME=$(basename "${BASH_SOURCE##*/}")
+if [ "$1" = '-h' ] || [ "$1" = '--help' ] || [ "$1" = '-help' ]; then
+    echo "Usage:"
+    echo "  $SCRIPT_NAME [vcd-fname]"
+    echo
+    echo "OPTIONS:"
+    echo "    vcd-fname"
+    echo "            Name of a vcd-file."
     exit 0
-} elseif {[string compare $arg0 "--help"] == 0} {
-    usage
-    exit 0
+fi
+
+FNAME=""
+
+find_file() {
+    IFS=$'\n' f_arr=($(find . -maxdepth 1 -type f \( -name "*.vcd" \)))
+    num_files=${#f_arr[@]}
+
+    if [ "$num_files" -eq 0 ]; then
+        echo "ERROR! Can't find dump file!"
+        exit 1
+    elif [ "$num_files" -gt 1 ]; then
+        echo "ERROR! There must be only one vcd-file in the directory!"
+        echo "Find files: ${f_arr[@]}"
+        exit 1
+    else
+        FNAME=${f_arr[0]}
+    fi
 }
 
-set dumpFname 0
-if {$argc == 1} {
-    set dumpFname [lindex $argv 0]
-    if {![file exists $dumpFname]} {
-        puts "ERROR! Can't find file $dumpFname!"
+if [ "$#" -eq 1 ]; then
+    FNAME="$1"
+    if [ ! -s "$FNAME" ]; then
+        echo "ERROR! Can't find input file: '$FNAME'!"
         exit 1
-    }
-}
+    fi
+else
+    find_file
+fi
 
-if {$dumpFname == 0} {
-    if {[catch {glob -type f *.vcd} resultVar]} {
-        puts "ERROR! Can't find dump file!"
-        puts stderr $resultVar
-        exit 1
-    }
-    set vcdFlist [glob -type f *.vcd]
-    set num_vcd [llength $vcdFlist]
-
-    if {$num_vcd != 1} {
-        puts "ERROR! There must be only one vcd-file in the directory!"
-        puts "Find file(s): $vcdFlist"
-        puts ""
-        usage
-        exit 1
-    } else {
-        set dumpFname [lindex $vcdFlist 0]
-    }
-}
-
-set script_path [file dirname [file normalize [info script]]]
-
-catch {exec gtkwave -S ${script_path}/gtkwave_cfg.tcl $dumpFname} resultVar
-puts $resultVar
-
-# FIXME: ERROR at Fedora Linux 35, x86_64, 5.17.6-200.fc35.x86_64:
-# This script does not work and crashes during opening with errors:
-# gtkwave: /opt/altera/19.1/quartus/linux64/liblzma.so.5: no version information available (required by gtkwave)
-# gtkwave: /opt/altera/19.1/quartus/linux64/liblzma.so.5: no version information available (required by /lib64/libxml2.so.2)
-# gtkwave: /opt/altera/19.1/quartus/linux64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /lib64/libicuuc.so.69)
-# gtkwave: /opt/altera/19.1/quartus/linux64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /lib64/libicui18n.so.69)
-# gtkwave: /opt/altera/19.1/quartus/linux64/liblzma.so.5: no version information available (required by /lib64/libsystemd.so.0)
+PATH2SCRIPT="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
+gtkwave -S "$PATH2SCRIPT"/gtkwave_cfg.tcl "$FNAME"
